name: starter
description: A new Flutter project.

publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.4.5
  flutter_riverpod: ^2.3.2
  go_router: ^6.4.0
  firebase_database: ^10.0.16
  firebase_ui_firestore: ^1.2.10
  dropdown_button2: ^2.0.0
  fluttertoast: ^8.2.1
  firebase_core: ^2.8.0
  shared_preferences: ^2.0.20
  firebase_auth: ^4.3.0
  firebase_ui_auth: ^1.1.17
  equatable: ^2.0.5
  rxdart: ^0.27.7
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  adaptive_navigation: ^0.0.9
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  riverpod_generator: ^2.1.4
  build_runner: ^2.3.3
  riverpod_lint: ^1.1.6
  mocktail: ^0.3.0
  riverpod_annotation: ^2.0.2
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
